### ISSUE TITLE
Remove unused social icons from Footer

### ISSUE THREAD

**Issue by SkSumit** [HackClubSKNCOE/NewForm#2]

**Comment by samankgupta** [comment]
Hi, can you assign it to me?

**Comment by SkSumit** [comment]
Sure

**Comment by Code-Recursion** [comment]
@SkSumit i would love to contribute which social icons to remove? please guide and assign it to me

**Comment by ShipraGaur** [comment]
Hi, I would like to contribute.

**Comment by SkSumit** [comment]
@ShipraGaur @Code-Recursion fairly easy task. Only make changes to footer section for this specific task. Whoever submits a valid PR first will be merged.
