### ISSUE TITLE
Make submit button align center.

### ISSUE THREAD

**Issue by SkSumit** [HackClubSKNCOE/NewForm#7]
Make the submit button (_views/index.html Line 200_) align to center to the form. Preferably use classes and helpers from [Bulma](http://bulma.io/)

**Comment by sharmashantanu** [comment]
Can you please assign me this task?

**Comment by fcoterroba** [comment]
I know do it too.

**Comment by SkSumit** [comment]
@fcoterroba Go ahead

**Comment by fcoterroba** [comment]
> @fcoterroba Go ahead

I did it an issue

**Comment by SHARUQ007** [comment]
> Make the submit button (_views/index.html Line 200_) align to center to the form. Preferably use classes and helpers from [Bulma](http://bulma.io/)

is it resolved? if not can i give it a go?
